spring:
  application:
    name: template1039
server:
  port: 8000
pocket:
  datasource:
    node:
      - url: jdbc:mysql://127.0.0.1:3306/basic?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true
        nodeName: mysql-01
        driverName: com.mysql.cj.jdbc.Driver
        showSql: true
        user: root
        password: root
        poolMiniSize: 5
        poolMaxSize: 50
        timeout: 1000
        session: biscuits,template

biscuits:
  serverId: 002
  stationId: 00501
